# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


target 'ProductivityApp' do
  rn_path = '../node_modules/react-native'
  node_modules = '../node_modules'

  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"
      
      targets_to_ignore = %w(React yoga)

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
 
    end
  end



end
